{
  "openapi": "3.0.3",
  "info": {
    "title": "MafakaMC API",
    "version": "2.0"
  },
  "servers": [
    {
      "url": "mafaka-api.vercel.app"
    },
    {
      "url": "http://localhost:3000"
    }
  ],
  "tags": [
    {
      "name": "Query",
      "description": "Consultar dados no banco de dados"
    },
    {
      "name": "Commit",
      "description": "Enviar dados para banco de dados"
    },
    {
      "name": "Download",
      "description": "下载文件"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "apiKey",
        "in": "header",
        "name": "Authentication"
      }
    }
  },
  "paths": {
    "/v2/projects": {
      "get": {
        "summary": "Obtenha lista de projetos",
        "tags": [
          "Query"
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "repo": {
                        "type": "string"
                      },
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "repo": "Exemplo/projeto",
                    "id": "project",
                    "name": "projectName"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}": {
      "get": {
        "summary": "Obtenha informações sobre um projeto específico",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_groups": {
                        "type": "array"
                      },
                      "versions": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version_groups": [
                    "1.20",
                    "1.19"
                  ],
                  "versions": [
                    "1.20.1",
                    "1.20",
                    "1.19.4",
                    "1.19.3",
                    "1.19.2",
                    "1.19.1",
                    "1.19"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}": {
      "get": {
        "summary": "Obtenha informações sobre a versão especificada do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version": "1.20",
                  "builds": [
                    1,
                    2,
                    3
                  ]
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds": {
      "get": {
        "summary": "Obtenha as informações de compilação da versão especificada do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version": "1.20",
                  "builds": [
                    {
                      "build": 1,
                      "time": "2023-08-03T06:12:14.887Z",
                      "channel": "default",
                      "promoted": false,
                      "changes": [
                        {
                          "commit": "hash",
                          "summary": "string",
                          "message": "string"
                        }
                      ],
                      "downloads": {
                        "application": {
                          "name": "xxx.jar",
                          "sha256": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/latestGroupBuildId": {
      "get": {
        "summary": "Obtenha o BuildID mais recente do grupo de versões especificado do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "text/plain": {
                "example": "12"
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/differ/{verRef}": {
      "get": {
        "summary": "Obtenha a diferença de ID entre o Ref (Git Hash) especificado e a versão mais recente da versão especificada do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "verRef",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "text/plain": {
                "example": "12"
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds/{build}": {
      "get": {
        "summary": "Obtenha informações sobre a compilação especificada da versão especificada do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "build",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version": {
                        "type": "string"
                      },
                      "build": {
                        "type": "integer"
                      },
                      "time": {
                        "type": "string"
                      },
                      "channel": {
                        "type": "string"
                      },
                      "promoted": {
                        "type": "boolean"
                      },
                      "changes": {
                        "type": "array"
                      },
                      "downloads": {
                        "type": "object"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version": "1.20",
                  "build": 1,
                  "time": "2023-08-03T06:12:14.887Z",
                  "channel": "default",
                  "promoted": false,
                  "changes": [
                    {
                      "commit": "hash",
                      "summary": "string",
                      "message": "string"
                    }
                  ],
                  "downloads": {
                    "application": {
                      "name": "xxx.jar",
                      "sha256": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/version_group/{family}": {
      "get": {
        "summary": "Obtém todas as subversões do grupo de versões especificado para o projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "family",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_group": {
                        "type": "string"
                      },
                      "versions": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version_group": "1.20",
                  "versions": [
                    "1.20.1",
                    "1.20"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/version_group/{family}/builds": {
      "get": {
        "summary": "Obtenha informações sobre todas as compilações do grupo de versões especificado do projeto especificado",
        "tags": [
          "Query"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "family",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "project_id": {
                        "type": "string"
                      },
                      "project_name": {
                        "type": "string"
                      },
                      "version_group": {
                        "type": "string"
                      },
                      "versions": {
                        "type": "array"
                      },
                      "builds": {
                        "type": "array"
                      }
                    }
                  }
                },
                "example": {
                  "code": 200,
                  "project_id": "leaves",
                  "project_name": "Leaves",
                  "version_group": "1.20",
                  "versions": [
                    "1.20.1",
                    "1.20"
                  ],
                  "builds": [
                    {
                      "build": 1,
                      "time": "2023-08-03T06:12:14.887Z",
                      "channel": "default",
                      "promoted": false,
                      "changes": [
                        {
                          "commit": "hash",
                          "summary": "string",
                          "message": "string"
                        }
                      ],
                      "downloads": {
                        "application": {
                          "name": "xxx.jar",
                          "sha256": "string"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}": {
      "get": {
        "summary": "Obtenha informações sobre a compilação especificada da versão especificada do projeto especificado",
        "tags": [
          "Download"
        ],
        "parameters": [
          {
            "name": "project",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "build",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "download",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "301": {
            "description": "sucesso",
            "content": {
              "application/java-archive": {}
            }
          },
          "404": {
            "description": "não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "integer"
                      },
                      "msg": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "code": 404,
                  "msg": "Not Found"
                }
              }
            }
          }
        }
      }
    },
    "/v2/commit/build": {
      "post": {
        "summary": "Envie um novo Build para o banco de dados",
        "tags": [
          "Commit"
        ],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "project_id": {
                    "type": "string"
                  },
                  "version": {
                    "type": "string"
                  },
                  "channel": {
                    "type": "string"
                  },
                  "changes": {
                    "type": "string"
                  },
                  "jar_name": {
                    "type": "string"
                  },
                  "sha256": {
                    "type": "string"
                  },
                  "tag": {
                    "type": "string"
                  }
                },
                "required": [
                  "project_id",
                  "version",
                  "channel",
                  "changes",
                  "jar_name",
                  "sha256",
                  "tag"]
              },
              "example": {
                "project_id": "leaves",
                "version": "1.20.1",
                "channel": "default",
                "changes": "changes",
                "jar_name": "leaves-1.20.1.jar",
                "sha256": "sha256",
                "tag": "1.20.1-1a2b3c4"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Envio bem-sucedido"
          },
          "400": {
            "description": "Erro de formato de solicitação"
          },
          "401": {
            "description": "Não autorizado"
          }
        }
      }
    }
  }
}
